Modern theme for split view component
blackbaud/skyux-split-view pull request #55
Opened 2021-05-17 20:48 UTC by Blackbaud-AlexKingman

2021-05-17 21:03 UTC, blackbaud-ado commented
Preview build at [https://developer.blackbaud.com/skyux-split-view?_sp.spa=pr-modern-theme](https://developer.blackbaud.com/skyux-split-view?_sp.spa=pr-modern-theme)

2021-05-18 14:28 UTC, Blackbaud-ToddRoberts requested changes
In responsive view, the "Back to list" button needs to use the sky icon font chevron in modern theme.

2021-05-18 14:28 UTC, Blackbaud-ToddRoberts commented on src/app/public/modules/split-view/split-view-workspace.component.scss
> +    border: 1px solid $sky-border-color-neutral-medium;
```suggestion
    border: 1px solid $sky-theme-modern-border-color-neutral-medium;
```

2021-05-18 15:03 UTC, blackbaud-ado commented
Preview build at [https://developer.blackbaud.com/skyux-split-view?_sp.spa=pr-modern-theme](https://developer.blackbaud.com/skyux-split-view?_sp.spa=pr-modern-theme)

2021-05-18 15:27 UTC, Blackbaud-AlexKingman commented on src/app/public/modules/split-view/split-view-workspace.component.ts
> +  }
☝️ Not a part of the scope of this PR, but `isMobile` was throwing an Expression Changed error if you loaded the page starting out in a small window. Moving the check to `ngOnInit` fixes the error.

2021-05-18 15:27 UTC, Blackbaud-AlexKingman commented
> In responsive view, the "Back to list" button needs to use the sky icon font chevron in modern theme.

Done.

2021-05-18 15:38 UTC, blackbaud-ado commented
Preview build at [https://developer.blackbaud.com/skyux-split-view?_sp.spa=pr-modern-theme](https://developer.blackbaud.com/skyux-split-view?_sp.spa=pr-modern-theme)

2021-05-18 20:34 UTC, blackbaud-ado commented
Preview build at [https://developer.blackbaud.com/skyux-split-view?_sp.spa=pr-modern-theme](https://developer.blackbaud.com/skyux-split-view?_sp.spa=pr-modern-theme)

2021-05-19 13:09 UTC, Blackbaud-ToddRoberts approved these changes

2021-05-19 14:13 UTC, johnhwhite approved these changes

2021-05-19 14:37 UTC, merged